import { useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { Animated, Easing, Modal, PanResponder, Platform, Pressable, StyleSheet, View, type StyleProp, type ViewStyle } from 'react-native';

type RenderChildren = ReactNode | ((dismiss: () => void) => ReactNode);
type SheetProps = { visible:boolean; onClose:()=>void; children:RenderChildren; style?:StyleProp<ViewStyle>; handleColor:string; backdropOpacity?:number; scrollAtTop?:boolean };
const SPRING={stiffness:300,damping:31,mass:.9,useNativeDriver:true} as const;
const WEB_GLASS=Platform.OS==='web'?({backdropFilter:'blur(18px) saturate(1.18)',WebkitBackdropFilter:'blur(18px) saturate(1.18)'} as any):undefined;

export function IOSSheet({visible,onClose,children,style,handleColor,backdropOpacity=.46,scrollAtTop=true}:SheetProps){
  const [mounted,setMounted]=useState(visible); const presentation=useRef(new Animated.Value(visible?1:0)).current; const dragY=useRef(new Animated.Value(0)).current; const closing=useRef(false); const sheetHeight=useRef(640); const scrollAtTopRef=useRef(scrollAtTop); const startedAtTop=useRef(scrollAtTop);
  useEffect(()=>{scrollAtTopRef.current=scrollAtTop},[scrollAtTop]);
  const animateOut=useCallback((notify:boolean)=>{if(closing.current)return;closing.current=true;Animated.parallel([Animated.timing(presentation,{toValue:0,duration:205,easing:Easing.bezier(.32,.72,0,1),useNativeDriver:true,isInteraction:false}),Animated.timing(dragY,{toValue:Math.max(360,sheetHeight.current+48),duration:235,easing:Easing.bezier(.32,.72,0,1),useNativeDriver:true,isInteraction:false})]).start(()=>{setMounted(false);if(notify)onClose()})},[dragY,onClose,presentation]);
  const dismiss=useCallback(()=>animateOut(true),[animateOut]);
  useEffect(()=>{if(!visible){if(mounted&&!closing.current)animateOut(false);closing.current=false;return}if(!mounted&&!closing.current)setMounted(true)},[animateOut,mounted,visible]);
  useEffect(()=>{if(!mounted||!visible||closing.current)return;presentation.stopAnimation();dragY.stopAnimation();presentation.setValue(0);dragY.setValue(0);requestAnimationFrame(()=>Animated.spring(presentation,{toValue:1,...SPRING,isInteraction:false}).start())},[dragY,mounted,presentation,visible]);
  const responder=useMemo(()=>PanResponder.create({onStartShouldSetPanResponderCapture:()=>{startedAtTop.current=scrollAtTopRef.current;return false},onMoveShouldSetPanResponder:(_,g)=>startedAtTop.current&&g.dy>4&&Math.abs(g.dy)>Math.abs(g.dx)*1.15,onPanResponderGrant:()=>dragY.stopAnimation(),onPanResponderMove:(_,g)=>{const raw=Math.max(0,g.dy);dragY.setValue(raw<=300?raw:300+(raw-300)*.28)},onPanResponderRelease:(_,g)=>{if(g.dy>82||(g.dy>20&&g.vy>.68))dismiss();else Animated.spring(dragY,{toValue:0,...SPRING,velocity:g.vy,isInteraction:false}).start()},onPanResponderTerminate:()=>Animated.spring(dragY,{toValue:0,...SPRING,isInteraction:false}).start(),onPanResponderTerminationRequest:()=>true}),[dismiss,dragY]);
  if(!mounted)return null; const introY=presentation.interpolate({inputRange:[0,1],outputRange:[24,0]}); const translateY=Animated.add(introY,dragY); const baseDim=presentation.interpolate({inputRange:[0,.28,1],outputRange:[0,backdropOpacity,backdropOpacity],extrapolate:'clamp'}); const dragDim=dragY.interpolate({inputRange:[0,480],outputRange:[1,0],extrapolate:'clamp'}); const content=typeof children==='function'?children(dismiss):children;
  return <Modal visible transparent animationType="none" presentationStyle="overFullScreen" onRequestClose={dismiss}><View style={styles.fill}><Animated.View pointerEvents="none" style={[StyleSheet.absoluteFill,styles.dim,{opacity:Animated.multiply(baseDim,dragDim)}]}/><Pressable style={StyleSheet.absoluteFill} onPress={dismiss}/><Animated.View pointerEvents="box-none" style={[styles.sheetMotion,{transform:[{translateY}]}]}><View onLayout={e=>{sheetHeight.current=e.nativeEvent.layout.height}} style={[styles.sheetBase,WEB_GLASS,style]} {...responder.panHandlers}><View style={styles.grabberTouch}><View style={[styles.grabber,{backgroundColor:handleColor}]}/></View>{content}</View></Animated.View></View></Modal>;
}
const styles=StyleSheet.create({fill:{flex:1,justifyContent:'flex-end'},dim:{backgroundColor:'#000'},sheetMotion:{width:'100%',height:'100%',alignSelf:'center',alignItems:'center',justifyContent:'flex-end'},sheetBase:{width:'100%',alignSelf:'center',shadowColor:'#000',shadowOffset:{width:0,height:-10},shadowOpacity:.16,shadowRadius:26,elevation:24},grabberTouch:{height:28,alignItems:'center',justifyContent:'center'},grabber:{width:36,height:5,borderRadius:3,opacity:.66}});
