import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, FlatList, Modal, Platform, Pressable, StyleSheet, Text, View, useColorScheme, useWindowDimensions } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { SwipeSurface } from './SwipeSurface';
import { pickAndParseRoster } from '@/src/import/pickRoster';
import type { ParsedAirAstanaRoster, RosterDuty, RosterSector } from '@/src/import/parseAirAstanaRoster';
import { clearStoredRosters, loadStoredRosters, removeStoredRoster, upsertStoredRoster } from '@/src/storage/rosterStorage';

type Tab='Home'|'Roster'|'More';
const TABS:Tab[]=['Home','Roster','More'];
const ICONS:Record<Tab,string>={Home:'⌂',Roster:'✈︎',More:'•••'};
type Palette={background:string;surface:string;surfaceStrong:string;text:string;muted:string;line:string;accent:string;accentSoft:string;gold:string;danger:string;weekend:string};
type DutyView={duty:RosterDuty;sectors:RosterSector[];date:string;report:string;release:string};

export default function MainScreen(){
  const scheme=useColorScheme(); const dark=scheme==='dark'; const {width}=useWindowDimensions(); const desktop=Platform.OS==='web'&&width>=768;
  const palette=useMemo<Palette>(()=>dark?{background:'#081519',surface:'rgba(15,34,39,.78)',surfaceStrong:'rgba(21,44,50,.88)',text:'#F3FAFA',muted:'#A8BABC',line:'rgba(174,214,216,.14)',accent:'#35B8C0',accentSoft:'rgba(53,184,192,.16)',gold:'#D4AE62',danger:'#E08383',weekend:'#DCA17B'}:{background:'#F2F6F6',surface:'rgba(255,255,255,.74)',surfaceStrong:'rgba(255,255,255,.92)',text:'#102326',muted:'#60777A',line:'rgba(16,74,79,.11)',accent:'#007F86',accentSoft:'#DFF1F2',gold:'#A67A24',danger:'#B84B52',weekend:'#9B613B'},[dark]);
  const [tab,setTab]=useState<Tab>('Home'); const [rosters,setRosters]=useState<ParsedAirAstanaRoster[]>([]); const [activeMonth,setActiveMonth]=useState<string>(); const [selected,setSelected]=useState<RosterSector>(); const [importing,setImporting]=useState(false); const [error,setError]=useState<string>();
  useEffect(()=>{const stored=loadStoredRosters();setRosters(stored);setActiveMonth(stored.at(-1)?.period.start)},[]);
  const roster=rosters.find(r=>r.period.start===activeMonth)??rosters.at(-1); const duties=useMemo(()=>roster?toDutyViews(roster):[],[roster]);
  const all=useMemo(()=>rosters.flatMap(r=>toDutyViews(r).map(d=>({roster:r,duty:d}))).sort((a,b)=>a.duty.date.localeCompare(b.duty.date)||a.duty.report.localeCompare(b.duty.report)),[rosters]);
  const changeTab=(delta:-1|1)=>{const n=TABS[TABS.indexOf(tab)+delta];if(n){setSelected(undefined);setTab(n)}};
  const importRoster=async()=>{setError(undefined);setImporting(true);try{const parsed=await pickAndParseRoster();if(!parsed)return;const next=upsertStoredRoster(parsed);setRosters(next);setActiveMonth(parsed.period.start);setTab('Roster')}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setImporting(false)}};
  const deleteRoster=(start:string)=>{const next=removeStoredRoster(start);setRosters(next);setActiveMonth(next.at(-1)?.period.start);setSelected(undefined)};
  const eraseAll=()=>{clearStoredRosters();setRosters([]);setActiveMonth(undefined);setSelected(undefined);setTab('Home')};
  return <SafeAreaView style={[styles.safe,{backgroundColor:palette.background}]} edges={desktop?['bottom']:['top','bottom']}><View style={styles.app}>
    <View style={styles.header}><View><Text style={[styles.brand,{color:palette.text}]}>eScrew</Text><Text style={[styles.kicker,{color:palette.muted}]}>CREW SCHEDULE</Text></View><View style={[styles.brandDot,{backgroundColor:palette.gold}]} /></View>
    <SwipeSurface style={styles.viewport} onSwipeLeft={tab==='More'?undefined:()=>changeTab(1)} onSwipeRight={tab==='Home'?undefined:()=>changeTab(-1)}>
      {tab==='Home'&&<Home all={all} palette={palette} onImport={importRoster} importing={importing}/>} 
      {tab==='Roster'&&<Roster roster={roster} rosters={rosters} duties={duties} palette={palette} selected={selected} error={error} importing={importing} onImport={importRoster} onSelect={setSelected} onMonth={setActiveMonth}/>} 
      {tab==='More'&&<More rosters={rosters} palette={palette} onDelete={deleteRoster} onErase={eraseAll}/>} 
    </SwipeSurface>
    <View style={[styles.tabBar,glass,{backgroundColor:palette.surface,borderColor:palette.line}]}>{TABS.map(item=><Pressable key={item} style={[styles.tabItem,item===tab&&{backgroundColor:palette.surfaceStrong}]} onPress={()=>{setSelected(undefined);setTab(item)}}><Text style={[styles.tabIcon,{color:item===tab?palette.accent:palette.muted}]}>{ICONS[item]}</Text><Text style={[styles.tabText,{color:item===tab?palette.text:palette.muted}]}>{item}</Text></Pressable>)}</View>
    <Modal visible={Boolean(selected)} transparent animationType="slide" onRequestClose={()=>setSelected(undefined)}>{selected&&<View style={styles.modalHost}><Pressable style={StyleSheet.absoluteFill} onPress={()=>setSelected(undefined)}/><View style={[styles.sheet,glass,{backgroundColor:palette.surfaceStrong,borderColor:palette.line}]}><View style={[styles.handle,{backgroundColor:palette.line}]}/><Text style={[styles.label,{color:palette.muted}]}>KC{selected.flightNumber}{selected.deadhead?' · DHC':''}</Text><Text style={[styles.sheetRoute,{color:palette.text}]}>{selected.departureAirport} → {selected.arrivalAirport}</Text><Text style={[styles.meta,{color:palette.muted}]}>{selected.date} · {selected.timeOut} – {selected.timeIn}</Text><Text style={[styles.meta,{color:palette.muted,marginTop:16}]}>Flight details are parsed locally from your imported roster.</Text></View></View>}</Modal>
  </View></SafeAreaView>;
}

function Home({all,palette,onImport,importing}:{all:{roster:ParsedAirAstanaRoster;duty:DutyView}[];palette:Palette;onImport:()=>void;importing:boolean}){
  const now=Date.now(); const focus=all.find(x=>stamp(x.duty.date,x.duty.report)>now)??all.at(-1); if(!focus)return <View style={styles.screen}><Text style={[styles.title,{color:palette.text}]}>Your roster, simplified.</Text><Text style={[styles.intro,{color:palette.muted}]}>Import an Air Astana Personal Crew Schedule Report.</Text><Primary title="Import roster PDF" onPress={onImport} loading={importing} palette={palette}/></View>;
  const {duty}=focus;const first=duty.sectors[0],last=duty.sectors.at(-1)!;const previous=all.filter(x=>stamp(x.duty.date,x.duty.release)<now&&x.duty!==duty).slice(-6).reverse();
  return <View style={styles.screen}><View style={styles.rowBetween}><Text style={[styles.label,{color:palette.accent}]}>NEXT DUTY</Text><Text style={[styles.label,{color:palette.muted}]}>{dateLabel(duty.date)}</Text></View><View style={[styles.hero,glass,{backgroundColor:palette.surfaceStrong,borderColor:palette.line}]}><Text numberOfLines={1} adjustsFontSizeToFit style={[styles.heroRoute,{color:palette.text}]}>{route(duty)}</Text><Text style={[styles.meta,{color:palette.muted}]}>{duty.sectors.map(s=>`KC${s.flightNumber}`).join(' · ')}</Text><View style={[styles.divider,{backgroundColor:palette.line}]}/><View style={styles.timeRow}><Time label="REPORT" value={duty.report} p={palette}/><Time label={`DEP · ${first.departureAirport}`} value={first.timeOut} p={palette}/><Time label={`ARR · ${last.arrivalAirport}`} value={last.timeIn} p={palette}/><Time label="RELEASE" value={duty.release} p={palette}/></View></View><Text style={[styles.label,{color:palette.muted}]}>PREVIOUS FLIGHTS</Text><FlatList data={previous} keyExtractor={x=>`${x.duty.date}-${x.duty.duty.index}`} showsVerticalScrollIndicator={false} renderItem={({item})=><View style={[styles.previous,{borderColor:palette.line}]}><Text style={[styles.prevDate,{color:palette.muted}]}>{dateLabel(item.duty.date)}</Text><Text numberOfLines={1} style={[styles.prevRoute,{color:palette.text}]}>{route(item.duty)}</Text><Text style={[styles.meta,{color:palette.muted}]}>{item.duty.release}</Text></View>}/></View>;
}

function Roster({roster,rosters,duties,palette,selected,error,importing,onImport,onSelect,onMonth}:{roster?:ParsedAirAstanaRoster;rosters:ParsedAirAstanaRoster[];duties:DutyView[];palette:Palette;selected?:RosterSector;error?:string;importing:boolean;onImport:()=>void;onSelect:(s?:RosterSector)=>void;onMonth:(s:string)=>void}){
  const flights=duties.flatMap(d=>d.sectors.map(s=>({duty:d,sector:s})));return <View style={styles.screen}><View style={styles.rowBetween}><View><Text style={[styles.title,{color:palette.text}]}>{roster?monthLabel(roster.period.start):'Roster'}</Text><Text style={[styles.meta,{color:palette.muted}]}>{roster?.subject?.base??'Personal schedule'}</Text></View><Pressable onPress={onImport} style={[styles.compact,{backgroundColor:palette.accentSoft}]}>{importing?<ActivityIndicator size="small"/>:<Text style={[styles.compactText,{color:palette.accent}]}>{roster?'Add PDF':'Import'}</Text>}</Pressable></View>{error&&<Text style={{color:palette.danger}}>{error}</Text>}{rosters.length>1&&<View style={styles.months}>{rosters.map(r=><Pressable key={r.period.start} onPress={()=>onMonth(r.period.start)} style={[styles.monthPill,{backgroundColor:r.period.start===roster?.period.start?palette.accentSoft:palette.surface}]}><Text style={[styles.meta,{color:r.period.start===roster?.period.start?palette.accent:palette.muted}]}>{monthLabel(r.period.start).split(' ')[0]}</Text></Pressable>)}</View>}{!roster?<View style={[styles.empty,{backgroundColor:palette.surface,borderColor:palette.line}]}><Text style={[styles.meta,{color:palette.muted}]}>Import a roster PDF to begin.</Text></View>:<View style={[styles.listWindow,{backgroundColor:palette.surface,borderColor:palette.line}]}><FlatList data={flights} keyExtractor={({sector})=>`${sector.date}-${sector.flightNumber}-${sector.dutySectorIndex}`} contentContainerStyle={styles.listContent} renderItem={({item})=><Pressable onPress={()=>onSelect(item.sector)} style={[styles.flightCard,{backgroundColor:selected===item.sector?palette.accentSoft:palette.surfaceStrong,borderColor:palette.line}]}><View style={styles.rowBetween}><Text style={[styles.label,{color:isWeekend(item.sector.date)?palette.weekend:palette.muted}]}>{dateLabel(item.sector.date)}</Text><Text style={[styles.label,{color:palette.muted}]}>KC{item.sector.flightNumber}{item.sector.deadhead?' · DHC':''}</Text></View><Text style={[styles.routeText,{color:palette.text}]}>{item.sector.departureAirport} → {item.sector.arrivalAirport}</Text><Text style={[styles.meta,{color:palette.muted}]}>{item.sector.timeOut} – {item.sector.timeIn} · Report {item.duty.report}</Text></Pressable>}/></View>}</View>;
}

function More({rosters,palette,onDelete,onErase}:{rosters:ParsedAirAstanaRoster[];palette:Palette;onDelete:(s:string)=>void;onErase:()=>void}){return <View style={styles.screen}><Text style={[styles.title,{color:palette.text}]}>More</Text><View style={[styles.info,glass,{backgroundColor:palette.surfaceStrong,borderColor:palette.line}]}><Text style={[styles.cardTitle,{color:palette.text}]}>Imported rosters</Text>{rosters.length?rosters.map(r=><View key={r.period.start} style={[styles.libraryRow,{borderColor:palette.line}]}><View style={{flex:1}}><Text style={[styles.cardTitle,{color:palette.text}]}>{monthLabel(r.period.start)}</Text><Text style={[styles.meta,{color:palette.muted}]}>{r.subject?.base??'Roster'} · parsed locally</Text></View><Pressable onPress={()=>onDelete(r.period.start)}><Text style={{color:palette.danger,fontWeight:'700'}}>Delete</Text></Pressable></View>):<Text style={[styles.meta,{color:palette.muted}]}>No months imported</Text>}</View><View style={[styles.info,glass,{backgroundColor:palette.surfaceStrong,borderColor:palette.line}]}><Text style={[styles.cardTitle,{color:palette.text}]}>Privacy</Text><Text style={[styles.meta,{color:palette.muted}]}>Roster PDFs are parsed locally. Source PDF bytes are not stored by eScrew.</Text></View>{rosters.length>0&&<Pressable onPress={onErase} style={[styles.erase,{borderColor:palette.line}]}><Text style={[styles.cardTitle,{color:palette.text}]}>Erase local roster data</Text></Pressable>}</View>}

function toDutyViews(roster:ParsedAirAstanaRoster):DutyView[]{return roster.duties.flatMap(duty=>{const sectors=roster.sectors.filter(s=>s.dutyIndex===duty.index);if(!sectors.length)return[];const first=sectors[0],last=sectors.at(-1)!;return[{duty,sectors,date:first.date,report:duty.start?.split('T')[1]??first.timeOut,release:duty.end?.split('T')[1]??last.timeIn}]})}
const route=(d:DutyView)=>[d.sectors[0]?.departureAirport,...d.sectors.map(s=>s.arrivalAirport)].filter(Boolean).join(' → ');
const monthLabel=(iso:string)=>new Intl.DateTimeFormat('en',{month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(iso+'T00:00:00Z')).toUpperCase();
const dateLabel=(iso:string)=>{const d=new Date(iso+'T00:00:00Z');return `${String(d.getUTCDate()).padStart(2,'0')} ${['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'][d.getUTCMonth()]}`};
const isWeekend=(iso:string)=>{const n=new Date(iso+'T00:00:00Z').getUTCDay();return n===0||n===6}; const stamp=(date:string,time:string)=>Date.parse(`${date}T${time}:00Z`);
function Time({label,value,p}:{label:string;value:string;p:Palette}){return <View style={styles.timeCell}><Text numberOfLines={1} style={[styles.timeLabel,{color:p.muted}]}>{label}</Text><Text style={[styles.timeValue,{color:p.text}]}>{value}</Text></View>}
function Primary({title,onPress,loading,palette}:{title:string;onPress:()=>void;loading:boolean;palette:Palette}){return <Pressable onPress={onPress} disabled={loading} style={[styles.primary,{backgroundColor:palette.accent}]}>{loading?<ActivityIndicator color="#fff"/>:<Text style={{color:'#fff',fontWeight:'700'}}>{title}</Text>}</Pressable>}
const glass=Platform.OS==='web'?({backdropFilter:'blur(24px) saturate(1.2)',WebkitBackdropFilter:'blur(24px) saturate(1.2)'} as any):undefined;
const styles=StyleSheet.create({safe:{flex:1},app:{flex:1,width:'100%',maxWidth:620,alignSelf:'center',paddingHorizontal:16},header:{height:72,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},brand:{fontSize:28,fontWeight:'800',letterSpacing:-1},kicker:{fontSize:10,fontWeight:'800',letterSpacing:1.4},brandDot:{width:10,height:10,borderRadius:5},viewport:{flex:1,minHeight:0},screen:{flex:1,paddingTop:8,gap:12},title:{fontSize:27,lineHeight:31,fontWeight:'700',letterSpacing:-.8},intro:{fontSize:15,lineHeight:22},label:{fontSize:11,fontWeight:'700',letterSpacing:.8},meta:{fontSize:13,lineHeight:18},rowBetween:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},hero:{borderWidth:1,borderRadius:26,padding:18,shadowColor:'#000',shadowOpacity:.09,shadowRadius:22,shadowOffset:{width:0,height:10}},heroRoute:{fontSize:35,lineHeight:41,fontWeight:'700',letterSpacing:-1},divider:{height:StyleSheet.hairlineWidth,marginVertical:14},timeRow:{flexDirection:'row',gap:5},timeCell:{flex:1,minWidth:0},timeLabel:{fontSize:9,fontWeight:'700'},timeValue:{fontSize:20,fontWeight:'700',marginTop:4,fontVariant:['tabular-nums']},previous:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:11,borderBottomWidth:StyleSheet.hairlineWidth},prevDate:{width:52,fontSize:11,fontWeight:'700'},prevRoute:{flex:1,fontSize:14,fontWeight:'600'},primary:{height:50,borderRadius:16,alignItems:'center',justifyContent:'center'},compact:{height:38,minWidth:72,borderRadius:14,alignItems:'center',justifyContent:'center',paddingHorizontal:12},compactText:{fontSize:12,fontWeight:'700'},months:{flexDirection:'row',gap:7,flexWrap:'wrap'},monthPill:{paddingHorizontal:10,paddingVertical:7,borderRadius:12},empty:{borderWidth:1,borderRadius:20,padding:16},listWindow:{flex:1,minHeight:0,borderWidth:1,borderRadius:20,overflow:'hidden'},listContent:{padding:8,gap:7,paddingBottom:18},flightCard:{borderWidth:1,borderRadius:16,padding:13},routeText:{fontSize:20,fontWeight:'700',marginTop:4},info:{borderWidth:1,borderRadius:20,padding:14,gap:8},cardTitle:{fontSize:15,fontWeight:'700'},libraryRow:{minHeight:58,flexDirection:'row',alignItems:'center',borderBottomWidth:StyleSheet.hairlineWidth,gap:10},erase:{height:48,borderWidth:1,borderRadius:15,alignItems:'center',justifyContent:'center'},tabBar:{height:68,marginTop:8,marginBottom:4,borderWidth:1,borderRadius:22,flexDirection:'row',padding:4,gap:4},tabItem:{flex:1,borderRadius:18,alignItems:'center',justifyContent:'center',gap:2},tabIcon:{fontSize:22,fontWeight:'700'},tabText:{fontSize:11,fontWeight:'600'},modalHost:{flex:1,backgroundColor:'rgba(0,0,0,.42)',justifyContent:'flex-end'},sheet:{width:'100%',maxWidth:620,alignSelf:'center',borderTopWidth:1,borderTopLeftRadius:28,borderTopRightRadius:28,padding:20,paddingBottom:34},handle:{width:38,height:5,borderRadius:3,alignSelf:'center',marginBottom:16},sheetRoute:{fontSize:30,fontWeight:'700',marginVertical:6}});
